### PR TITLE
David/docs/improvements

### PR DESCRIPTION
**Pull request by David-Pena**
This PR includes:
- Fix typo `reccomended` to `recommended`
- Add emojis to titles and reorganize ruleset paragraph in `get-started.md`

### CODE REVIEW

**Comment by David-Pena** [comment]
I'm used to do pair code review when working with other people. I'm wondering if:
- Do you want me to ask for your review in all cases before pushing to a main branch? 
- Or just for specific PRs (like core-funcionality changes, new rule)?

i.e this PR is only UI changes and typos, should I just push it to `72-create-docs-site` branch?

What do you think? @rrd108

**Comment by rrd108** [comment]
> * Do you want me to ask for your review in all cases before pushing to a main branch?

It is up to you. If you are more confortable with that I can review them. Maybe we can add the same check for pushing to the main branch what we have for PR-s. So at least we are sure all tests are passing.
We can use feature branches, so we do not flood the main branch.

> * Or just for specific PRs (like core-funcionality changes, new rule)?

Up to you :smile:

**Comment by David-Pena** [comment]
> It is up to you. If you are more confortable with that I can review them.

For now I think I'll ask for review for core changes/new rules, but typos and minor things like that I'll merge it by myself. I hope that's okay with you 🧑🏼‍💻

> Maybe we can add the same check for pushing to the main branch what we have for PR-s. So at least we are sure all tests are passing.

Agreed, is that a GH action?

> We can use feature branches, so we do not flood the main branch.

🫡

**Comment by rrd108** [comment]
> For now I think I'll ask for review for core changes/new rules, but typos and minor things like that I'll merge it by myself. I hope that's okay with you 🧑🏼‍💻

:+1: 

> Agreed, is that a GH action?

Yep, it is added cbf117d6311cebe5ae0c608a3e5fcaa83a364528

**Pull request merged**
