### PR TITLE
feat: Add linter, VSCode settings

### PR DESCRIPTION
**Pull request by bchanez**
Related to https://github.com/rrd108/vue-mess-detector/issues/73

- Added linter configuration to the project
- Added recommended extensions for VSCode
- Added VSCode settings to enable auto-fixing of linting issues on file save

### CODE REVIEW

**Comment by David-Pena** [comment]
Maybe the linter integration should be its own PR and another PR for a full lint fix in the codebase?

**Comment by rrd108** [comment]
@bchanez Thank you for submitting this pull request! We really appreciate your contribution to the project.

I noticed that the tests are currently failing for this PR. This is a common occurrence and nothing to worry about - it's part of the process of integrating new code.

To help move this forward:

1. Could you please check the CI/CD logs to see which specific test(s) are failing?
2. Once identified, try running these tests locally to reproduce the issue.
3. Make any necessary adjustments to your code to address the failing tests.

If you're having trouble understanding the test failures or need any help resolving them, please don't hesitate to ask. We're here to help!

Let me know if you have any questions or if there's anything I can do to assist you in getting this PR ready for merge.

Thanks again for your contribution!

**Comment by David-Pena** [comment]
I have a question, to use this linter do I need to setup something? or just by having the latest changes is enough? @bchanez

**Comment by bchanez** [comment]
@David-Pena just add recommended extensions and everything should be fine

**Pull request merged**
