### PR TITLE
change createMarkdown to createDoc

### LINKED ISSUE #177: Refactor rename `createMarkdown` to `createDoc`
`createMarkdown.js` to `createDoc.js` and corresponding `package.json` script and doc examples

### PR DESCRIPTION
**Pull request by AlexVCS**
### Summary

change createMarkdown to createDoc

### Description

change createMarkdown to createDoc and change reference to it in package.json closes #177 

### Related Issues
Fixes #177 

### Type of Change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

### CODE REVIEW

**Review by rrd108 — APPROVED** [review]

**Review by David-Pena — APPROVED** [review]

**Comment by David-Pena** [comment]
Thanks for your contribution @AlexVCS  🚀

**Comment by rrd108** [comment]
Look what happened here 

Képernyőkép 2024-08-23 18-07-06

**Comment by David-Pena** [comment]
There were only three a month ago basically 🤯

**Comment by AlexVCS** [comment]
Wow! Happy to be there, thanks!

**Comment by rrd108** [comment]
Welcome

**Pull request merged**
