### PR TITLE
feat: add pkg-pr-new action

### LINKED ISSUE #184: Add pkg.pr.new to approved pull requests
Seems to be easy to integrate [docs](https://github.com/stackblitz-labs/pkg.pr.new) and useful GitHub Action for continuous releases

### PR DESCRIPTION
**Pull request by David-Pena**
### Summary
Adds [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new) for continuous releases

### Description
- GH App installed by @rrd108 
- Added `continuous-release.yml`

### Related Issues
Fixes #184 

### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

### CODE REVIEW

**Comment by David-Pena** [comment]
Waiting for some clarification about how to avoid duplicate releases on tags 
https://github.com/stackblitz-labs/pkg.pr.new/issues/140#issuecomment-2337006580

**Comment by David-Pena** [comment]
Ready for review @rrd108

**Review by rrd108 — APPROVED** [review]

**Comment by rrd108** [comment]
Autofix complaints, run a `yarn lint` on your end

**Comment by David-Pena** [comment]
>  Autofix complaints, run a yarn lint on your end

Just pushed fixes from `yarn lint:fix`

**Review by rrd108 — APPROVED** [review]

**Pull request merged**
