### PR TITLE
feat: enable --apply/--ignore flags to handle rules and rulesets via command / config file

### LINKED ISSUE #63: Add cli option to `ignore` and `apply` rulesets/rules
### Discussed in https://github.com/rrd108/vue-mess-detector/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **David-Pena** July 18, 2024</sup>
Now that you mentioned adding a `group` flag to the `analyze` command in #5, I was wondering what do you think about a feature to toggle on/off rules? (Being this package kind of opinionated for some rules)

And I picture this like though the `analyze` command too, like with the flag `toggle` it will prompt like a CLI to select wich rules you want to apply to the check or not.

But I have no idea how can that be done, or if its worth it so I'll just let the idea here in discussion 👨‍💻</div>

### PR DESCRIPTION
**Pull request by David-Pena**
### Summary
Enable the `--apply` | `--ignore` flag to receive as input rulesets and/or individual rules

### Description
- [X] Update `choices` and titles in the `--apply` flag in `src/index.ts` 
- [X] Update `choices` and titles in the `--ignore` flag in `src/index.ts`
- [X] Refactor `analyzer.ts` to include new logic for `--apply` flag,  and some comments were added
- [X] Refactor `coerceRules.ts` to include new logic for `--apply` flag
- [X] New util function created `groupRulesByRuleset`
- [X] Add more tests in `index.test.ts`
- [X] Apply all from above ⬆️ but with `--ignore` flag

### Related Issues
Fixes #63 
Discussed in #62 

### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Documentation update

### Screenshots (if applicable)
image
image
image

### CODE REVIEW

**Comment by David-Pena** [comment]
The `pull_request` CI is failing probably because I dont upload the `dist` folder to GH.

I won't check in details that because this PR is not ready to merge, when I finished the `ignore` implementation, I'll check if my theory is true for the CI test

**Comment by rrd108** [comment]
Isn't it the same?

**Comment by rrd108** [comment]
I mean in both cases we build up the apply array

**Comment by David-Pena** [comment]
> Isn't it the same?

I mean, whats the hierarchy? if I send the `--ignore` in command line, should I ignore the `--apply` in the config file? or viceversa?

**Comment by David-Pena** [comment]
I add a comment on a test that I think should fail @rrd108 , because I deleted the `check` where the condition is so Im not sure how that test is passing.

Beyond that, I think everything is working, you can try the `--apply` and `--ignore` feature

**Review by rrd108 — APPROVED** [review]

**Pull request merged**
