### PR TITLE
feat: add contribution guide

### PR DESCRIPTION
**Pull request by David-Pena**

### CODE REVIEW

**Comment by rrd108** [comment]
I wanted to add this next week.

You were quicker David 🙏

**Comment by David-Pena** [comment]
I'm just excited with this project 👌👨‍💻

**Comment by David-Pena** [comment]
@rrd108 I just realized the link inside the README was redirecting to my branch
image

Let me know if you can change it on the next release or if you want, I can send a small pr for this

**Comment by rrd108** [comment]
Ah I missed then when I reviewed. Sure send a pr

**Comment by David-Pena** [comment]
#70 created for the link issue

**Pull request merged**
