### PR TITLE
CLI prints project version number

### LINKED ISSUE #427: Version not working
**Describe the bug**

The version number is giving the version number of my project, not of the version of the vue-mess-detector.

**To Reproduce**

Install within a project, run either `yarn vue-mess-detector analyze --version` or `yarn vue-mess-detector --version` or `./node_modules/vue-mess-detector/dist/cliStart.js --version`, prints out whatever the projects package.json version is.

**Expected behavior**

Expect to see version 0.63.1.

**Screenshots**

**Used version number of vue-mess-detector:**

0.63.1

**Used version number of node & yarn:**

yarn version v3.8.2 and node v20.17.0

**Additional context**
Might just be for me?

### PR DESCRIPTION
**Pull request by pieterocp**
### Summary

Gets version printing out project specific version number. Helpful for bug reports/checking versions at a glance.

### Description

Should get the version number printing. Still need to pull it into a project and test but I want to say this does it.

### Related Issues
Fixes #427 

### Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
    - I hope nobody has been depending on this to work this way, but if they have, that's on them.
- [ ] Documentation update

### CODE REVIEW

**Comment by David-Pena** [comment]
There are some tests failing, could you check them out?
For example this one of the `cli.test.ts` image

**Comment by pieterocp** [comment]
> There are some tests failing, could you check them out? For example this one of the `cli.test.ts` image

Thinking about it, testing version just feels a bit like much, a bit of overhead to add to every test run.

**Comment by pieterocp** [comment]
I'm struggling with these failing tests, locally without any changes they are mostly timing out even when set to 20 seconds, feel free to make grand sweeping changes @David-Pena

**Comment by pieterocp** [comment]
@David-Pena or @rrd108 this is ready for a review. Please do check it out and give it a waltz yourselves since I still couldn't get any cli tests to run locally after a bunch of changes so 🤷

**Comment by David-Pena** [comment]
On my end I have similar issues with the tests (still trying to figure out why) probably @rrd108 can check it out soon

**Comment by David-Pena** [comment]
I see all checks have passed @pieterocp

**Comment by David-Pena** [comment]
But I open your changes in Stackblitz and the `--version` seems to still not be working
image

**Comment by rrd108** [comment]
Sorry for not replying, I was (I am) sick.

I do not think that changing the tests is needed here. I think the bug sits somewhere else.

**Comment by rrd108** [comment]
Let me investigate it further.

**Comment by David-Pena** [comment]
Hi @pieterocp 

I found and fixed this issue locally, it was happening because the flag was retrieving the `version` field instead of the 'vue-mess-detector' value from `dependencies or devDependencies`

Would you like me to push my code to your branch so we can move forward this PR? Or would you like to give a try?

**Comment by pieterocp** [comment]
>Would you like me to push my code to your branch so we can move forward this PR? ~~Or would you like to give a try?~~

Go for it @David-Pena, thank you.

**Comment by David-Pena** [comment]
Got it! I'll push it in a moment 🫡

**Comment by David-Pena** [comment]
This PR will be closed, the fix is in #461

**Pull request closed without merging**
