### PR TITLE
feat: output explanation

### PR DESCRIPTION
**Pull request by Whomy09**

### CODE REVIEW

**Comment by David-Pena** [comment]
I like the content and structure of the explanation, I noticed a few wordings that might be a bit confusing, check it out this markdown with a few changes in the wordings, and let me know what do you think? @Whomy09

⬇️

Group by Rule: In this view, the first line is highlighted in blue, representing the rule being evaluated. Following this, you'll see blocks of information structured as follows: file path, description, and message.

Group by File: In this view, the first line displays the file path being evaluated. Below this, you'll see blocks of information with the following structure: rule, description, and message.

Rule: The blue line that defines the specific rule being evaluated.
File: Shows the path to the file where the rule is applied.
Description: A concise explanation of the rule, often accompanied by a link to relevant documentation for further details.
Message: Indicates the line of code where the rule was violated. Yellow messages are warnings, suggesting best practices, while red messages highlight errors that must be corrected.
⬆️

**Comment by David-Pena** [comment]
Also, this issue was about adding the output explanation to the docs, not to the README

Maybe we can leave it in both places? @rrd108

**Review by David-Pena — CHANGES_REQUESTED** [review]
Please check comments

**Comment by rrd108** [comment]
Yes I think README should contain all the basics, including this.

**Review by David-Pena — APPROVED** [review]

**Pull request merged**
