### PR TITLE
Feature/ignore rules for file

### PR DESCRIPTION
**Pull request by ryan-williams-nourish**
### Summary
I have created a new capability to ignore specific rules for specific files (or indeed file matchers) by adding the following to the vue-mess-detector.json:

```
"fileIgnoreRules": {
    "src/main.ts": "tooManyProps,computedSideEffects",
    "src/router/index.ts": "noConsole,multiAttributeElements"
  }
```

### Description
1. I added a fileIgnoreRules to your config object, an array of string:string records.
2. I added the field to the analyse method and updated output to let the user know what files we're ignoring rules for
3. I updated checkFile to update the apply value to remove rules listed in matching files, with that capability pushed out to a checkFileIgnoreRules method.

### Related Issues
N/A

### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

### Screenshots (if applicable)
N/A

### CODE REVIEW

**Comment by David-Pena** [comment]
Thanks for your contribution 🙌 It caught my interest since you mentioned it on Discord.

I wonder how would this new config option work with the current `--apply` and `--ignore` flags, right now those two flags can't be used together... 

Let's suppose this is my `vue-mess-detector.json`
```js
{
    apply: "vue-strong, rrd",
    "fileIgnoreRules": {
        "src/main.ts": "tooManyProps"
     }
}
```

In the ⬆️ case, we are indicating we want to `apply` the `rrd` ruleset and also indicating that we want to ignore `tooManyProps` rule from the analyzer in a specific file, but `tooManyProps` belong to the `rrd` ruleset we set to be applied, what would happen?

**Review by David-Pena — APPROVED** [review]
LGTM 🫡 @rrd108

**Comment by rrd108** [comment]
> I wonder how would this new config option work with the current `--apply` and `--ignore` flags, right now those two flags can't be used together...

@ryan-williams-nourish Can you answer this?
We should update the docs accordingly.

**Comment by idontwantyourspamthanks** [comment]
> > I wonder how would this new config option work with the current `--apply` and `--ignore` flags, right now those two flags can't be used together...
> 
> @ryan-williams-nourish Can you answer this? We should update the docs accordingly.

So this happens downstream of --ignore and --apply actions - so whatever's come through the pipe, which is a list of rules that will be globally enforced, ends up being pruned for each file according to the ignore list for that file.

**Comment by ryan-williams-nourish** [comment]
> > I wonder how would this new config option work with the current `--apply` and `--ignore` flags, right now those two flags can't be used together...
> 
> @ryan-williams-nourish Can you answer this? We should update the docs accordingly.

Apologies - thought we had covered in Discord but possibly not. So my file ignore stuff happens downstream of the --ignore and --apply stuff - it thus receives a list of rules that are active, and for each file it will trim off rules that should not be applied. As such it can coexist with either and doesn't do anything to change the state of either.

**Comment by ryan-williams-nourish** [comment]
> > > I wonder how would this new config option work with the current `--apply` and `--ignore` flags, right now those two flags can't be used together...
> > 
> > 
> > @ryan-williams-nourish Can you answer this? We should update the docs accordingly.
> 
> Apologies - thought we had covered in Discord but possibly not. So my file ignore stuff happens downstream of the --ignore and --apply stuff - it thus receives a list of rules that are active, and for each file it will trim off rules that should not be applied. As such it can coexist with either and doesn't do anything to change the state of either.

Forgot to add - I'll try to get the docs updated today if I can get a bit of time. Wife's got some TV scheduled tonight so I reckon I'll get some coding time.

**Comment by ryan-williams-nourish** [comment]
> > I wonder how would this new config option work with the current `--apply` and `--ignore` flags, right now those two flags can't be used together...
> 
> @ryan-williams-nourish Can you answer this? We should update the docs accordingly.

Docs added and explanation above. I tried to find a nice way to do this in CLI btw and couldn't find one so I've concluded this one is for json only for now. Hope that's ok.

**Review by rrd108 — APPROVED** [review]

**Pull request merged**
